name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Light Mode SVG
      - name: Generate Pacman Contribution Graph (Light)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: github-light
          output_file: pacman-contribution-graph-light.svg

      # Generate Dark Mode SVG
      - name: Generate Pacman Contribution Graph (Dark)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: dracula
          output_file: pacman-contribution-graph-dark.svg

      - name: Push SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
